<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Thống kê mô tả cơ bản | Giới thiệu cơ bản về XSTK</title>
  <meta name="description" content="6 Thống kê mô tả cơ bản | Giới thiệu cơ bản về XSTK" />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Thống kê mô tả cơ bản | Giới thiệu cơ bản về XSTK" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="truonghm/stat101" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Thống kê mô tả cơ bản | Giới thiệu cơ bản về XSTK" />
  
  
  

<meta name="author" content="Truong Hoang" />


<meta name="date" content="2020-11-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="xác-su-t-c-b-n.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="motivation.html"><a href="motivation.html"><i class="fa fa-check"></i>Motivation</a></li>
<li class="chapter" data-level="1" data-path="draft-outline.html"><a href="draft-outline.html"><i class="fa fa-check"></i><b>1</b> Draft outline</a></li>
<li class="chapter" data-level="2" data-path="to-do.html"><a href="to-do.html"><i class="fa fa-check"></i><b>2</b> To-do</a></li>
<li class="chapter" data-level="3" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>3</b> References</a></li>
<li class="part"><span><b>Kiến thức cơ bản</b></span></li>
<li class="chapter" data-level="4" data-path="review-l-i-toán.html"><a href="review-l-i-toán.html"><i class="fa fa-check"></i><b>4</b> Review lại toán</a><ul>
<li class="chapter" data-level="4.1" data-path="review-l-i-toán.html"><a href="review-l-i-toán.html#đạo-hàm-và-tính-phân"><i class="fa fa-check"></i><b>4.1</b> Đạo hàm và tính phân</a></li>
<li class="chapter" data-level="4.2" data-path="review-l-i-toán.html"><a href="review-l-i-toán.html#định-nghĩa-e"><i class="fa fa-check"></i><b>4.2</b> Định nghĩa <span class="math inline">\(e\)</span></a></li>
<li class="chapter" data-level="4.3" data-path="review-l-i-toán.html"><a href="review-l-i-toán.html#tổ-hợp-chỉnh-hợp-và-hoán-vị"><i class="fa fa-check"></i><b>4.3</b> Tổ hợp, chỉnh hợp và hoán vị</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html"><i class="fa fa-check"></i><b>5</b> Xác suất cơ bản</a><ul>
<li class="chapter" data-level="5.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#một-số-định-nghĩa-cơ-bản"><i class="fa fa-check"></i><b>5.1</b> Một số định nghĩa cơ bản</a></li>
<li class="chapter" data-level="5.2" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#lý-thuyết-tập-hợp"><i class="fa fa-check"></i><b>5.2</b> Lý thuyết tập hợp</a><ul>
<li class="chapter" data-level="5.2.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#biểu-đồ-venn"><i class="fa fa-check"></i><b>5.2.1</b> Biểu đồ Venn</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#các-phép-toánquan-hệ-tập-hợp"><i class="fa fa-check"></i><b>5.3</b> Các phép toán/quan hệ tập hợp</a><ul>
<li class="chapter" data-level="5.3.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#phép-hợp-union"><i class="fa fa-check"></i><b>5.3.1</b> Phép hợp (Union)</a></li>
<li class="chapter" data-level="5.3.2" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#phép-giao-intersection"><i class="fa fa-check"></i><b>5.3.2</b> Phép giao (intersection)</a></li>
<li class="chapter" data-level="5.3.3" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#phần-bù-complement"><i class="fa fa-check"></i><b>5.3.3</b> Phần bù (Complement)</a></li>
<li class="chapter" data-level="5.3.4" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#loại-trừ-lẫn-nhau-mutually-exclusive"><i class="fa fa-check"></i><b>5.3.4</b> Loại trừ lẫn nhau (Mutually exclusive)</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#quy-luật-xác-suất"><i class="fa fa-check"></i><b>5.4</b> Quy luật xác suất</a><ul>
<li class="chapter" data-level="5.4.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#các-quy-luật-cơ-bản"><i class="fa fa-check"></i><b>5.4.1</b> Các quy luật cơ bản</a></li>
<li class="chapter" data-level="5.4.2" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#xác-suất-có-điều-kiện-conditional-probability"><i class="fa fa-check"></i><b>5.4.2</b> Xác suất có điều kiện (conditional probability)</a></li>
<li class="chapter" data-level="5.4.3" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#tổng-hợp-quy-luật-xác-suất"><i class="fa fa-check"></i><b>5.4.3</b> Tổng hợp quy luật xác suất</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#biến-ngẫu-nhiên-rời-rạc"><i class="fa fa-check"></i><b>5.5</b> Biến ngẫu nhiên rời rạc</a><ul>
<li class="chapter" data-level="5.5.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#giới-thiệu-về-biến-ngẫu-nhiên-rời-rạc-nnrr"><i class="fa fa-check"></i><b>5.5.1</b> Giới thiệu về biến ngẫu nhiên rời rạc (NNRR)</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#các-phân-phối-rời-rạc-phổ-biến"><i class="fa fa-check"></i><b>5.6</b> Các phân phối rời rạc phổ biến</a><ul>
<li class="chapter" data-level="5.6.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#binomial-distribution---pp-nhị-thức"><i class="fa fa-check"></i><b>5.6.1</b> Binomial distribution - PP nhị thức</a></li>
<li class="chapter" data-level="5.6.2" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#poisson-distribution---pp-poisson"><i class="fa fa-check"></i><b>5.6.2</b> Poisson distribution - PP Poisson</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#biến-ngẫu-nhiên-liên-tục"><i class="fa fa-check"></i><b>5.7</b> Biến ngẫu nhiên liên tục</a><ul>
<li class="chapter" data-level="5.7.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#pdf-cdf-và-ccdf"><i class="fa fa-check"></i><b>5.7.1</b> PDF, CDF và CCDF</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#các-phân-phối-liên-tục-phổ-biến"><i class="fa fa-check"></i><b>5.8</b> Các phân phối liên tục phổ biến</a><ul>
<li class="chapter" data-level="5.8.1" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#exponential-distribution---pp-mũ"><i class="fa fa-check"></i><b>5.8.1</b> Exponential distribution - PP mũ</a></li>
<li class="chapter" data-level="5.8.2" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#uniform-01-distribution"><i class="fa fa-check"></i><b>5.8.2</b> Uniform [0,1] distribution</a></li>
<li class="chapter" data-level="5.8.3" data-path="xác-su-t-c-b-n.html"><a href="xác-su-t-c-b-n.html#normal-distribution"><i class="fa fa-check"></i><b>5.8.3</b> Normal distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html"><i class="fa fa-check"></i><b>6</b> Thống kê mô tả cơ bản</a><ul>
<li class="chapter" data-level="6.1" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#tóm-tắt-dữ-liệu-qua-đồ-thị"><i class="fa fa-check"></i><b>6.1</b> Tóm tắt dữ liệu qua đồ thị</a><ul>
<li class="chapter" data-level="6.1.1" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#một-biến-rời-rạc-univariate"><i class="fa fa-check"></i><b>6.1.1</b> Một biến rời rạc (univariate)</a></li>
<li class="chapter" data-level="6.1.2" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#một-biến-liên-tục-univariate"><i class="fa fa-check"></i><b>6.1.2</b> Một biến liên tục (univariate)</a></li>
<li class="chapter" data-level="6.1.3" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#một-biến-rời-rạc-và-một-biến-liên-tục-bivariate"><i class="fa fa-check"></i><b>6.1.3</b> Một biến rời rạc và một biến liên tục (bivariate)</a></li>
<li class="chapter" data-level="6.1.4" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#hai-biến-liên-tục-bivariate"><i class="fa fa-check"></i><b>6.1.4</b> Hai biến liên tục (bivariate)</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#xu-hướng-trung-tâm"><i class="fa fa-check"></i><b>6.2</b> Xu hướng trung tâm</a><ul>
<li class="chapter" data-level="6.2.1" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#mean-trung-bình-cộng"><i class="fa fa-check"></i><b>6.2.1</b> Mean (Trung bình cộng)</a></li>
<li class="chapter" data-level="6.2.2" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#median-trung-vị"><i class="fa fa-check"></i><b>6.2.2</b> Median (Trung vị)</a></li>
<li class="chapter" data-level="6.2.3" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#trimmed-mean"><i class="fa fa-check"></i><b>6.2.3</b> Trimmed mean</a></li>
<li class="chapter" data-level="6.2.4" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#ví-dụ"><i class="fa fa-check"></i><b>6.2.4</b> Ví dụ</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#mức-độ-phân-tán-spreaddispersion"><i class="fa fa-check"></i><b>6.3</b> Mức độ phân tán (Spread/Dispersion)</a><ul>
<li class="chapter" data-level="6.3.1" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#range-khoảng-biến-thiên"><i class="fa fa-check"></i><b>6.3.1</b> Range (Khoảng biến thiên)</a></li>
<li class="chapter" data-level="6.3.2" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#inter-quartile-range"><i class="fa fa-check"></i><b>6.3.2</b> Inter-Quartile Range</a></li>
<li class="chapter" data-level="6.3.3" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#variance-phương-sai"><i class="fa fa-check"></i><b>6.3.3</b> Variance (Phương sai)</a></li>
<li class="chapter" data-level="6.3.4" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#standard-variation-độ-lệch-chuẩn"><i class="fa fa-check"></i><b>6.3.4</b> Standard variation (độ lệch chuẩn)</a></li>
<li class="chapter" data-level="6.3.5" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#hệ-số-biến-thiên-coefficient-of-variation"><i class="fa fa-check"></i><b>6.3.5</b> Hệ số biến thiên (Coefficient of variation)</a></li>
<li class="chapter" data-level="6.3.6" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#quy-tắc-thực-nghiệm"><i class="fa fa-check"></i><b>6.3.6</b> Quy tắc thực nghiệm</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#tiếp-tục-với-biểu-đồ"><i class="fa fa-check"></i><b>6.4</b> Tiếp tục với biểu đồ</a><ul>
<li class="chapter" data-level="6.4.1" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#box-plot"><i class="fa fa-check"></i><b>6.4.1</b> Box plot</a></li>
<li class="chapter" data-level="6.4.2" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#scatter-plot"><i class="fa fa-check"></i><b>6.4.2</b> Scatter plot</a></li>
<li class="chapter" data-level="6.4.3" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#skewness-kurtosis"><i class="fa fa-check"></i><b>6.4.3</b> Skewness &amp; Kurtosis</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#tổng-hợp-thuật-ngữ"><i class="fa fa-check"></i><b>6.5</b> Tổng hợp thuật ngữ</a></li>
<li class="chapter" data-level="6.6" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#một-số-bài-tập"><i class="fa fa-check"></i><b>6.6</b> Một số bài tập</a></li>
<li class="chapter" data-level="6.7" data-path="th-ng-kê-mô-t-c-b-n.html"><a href="th-ng-kê-mô-t-c-b-n.html#tham-khảo"><i class="fa fa-check"></i><b>6.7</b> Tham khảo</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Giới thiệu cơ bản về XSTK</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thống-kê-mô-tả-cơ-bản" class="section level1">
<h1><span class="header-section-number">6</span> Thống kê mô tả cơ bản</h1>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="co"># load sẵn ggplot2 (đã bao gồm trong tidyverse)</span></a>
<a class="sourceLine" id="cb16-2" title="2"><span class="kw">library</span>(tidyverse, <span class="dt">quietly =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Summary statistics (thống kê mô tả tóm tắt) là một phần cơ bản trong khoa học thống kê, giúp chúng ta mô tả ngắn gọn dữ liệu thông qua các chỉ số thống kê cơ bản nhất. Đồng thời, chúng ta cũng sử dụng các công cụ visualization trong R để đưa data trở thành 1 biểu đồ mang mục đích tóm tắt.</p>
<p>Trong phần này, chúng ta sẽ sử dụng dataset <code>TenMileRace</code> từ package <strong>mosaicData</strong>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="co"># Cài package nếu chưa có sẵn</span></a>
<a class="sourceLine" id="cb17-2" title="2"><span class="kw">install.packages</span>(<span class="st">&#39;mosaicData&#39;</span>)</a></code></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">data</span>(TenMileRace, <span class="dt">package=</span><span class="st">&#39;mosaicData&#39;</span>)</a>
<a class="sourceLine" id="cb18-2" title="2"><span class="kw">summary</span>(TenMileRace)</a></code></pre></div>
<pre><code>##      state           time            net             age        sex     
##  VA     :3689   Min.   : 2816   Min.   : 2814   Min.   :10.00   F:4325  
##  MD     :2166   1st Qu.: 5125   1st Qu.: 4950   1st Qu.:28.00   M:4311  
##  DC     :1642   Median : 5806   Median : 5555   Median :35.00           
##  PA     : 273   Mean   : 5813   Mean   : 5599   Mean   :36.86           
##  NY     : 211   3rd Qu.: 6455   3rd Qu.: 6169   3rd Qu.:44.00           
##  NJ     :  92   Max.   :10603   Max.   :10536   Max.   :87.00           
##  (Other): 563</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">head</span>(TenMileRace)</a></code></pre></div>
<pre><code>##   state time  net age sex
## 1    VA 6060 5978  12   M
## 2    MD 4515 4457  13   M
## 3    VA 5026 4928  13   M
## 4    MD 4229 4229  14   M
## 5    MD 5293 5076  14   M
## 6    VA 6234 5968  14   M</code></pre>
<p>Dataset này có các cột sau:</p>
<ul>
<li><p><code>state</code>: Là nơi sống của người chạy.</p></li>
<li><p><code>time</code>: Thời gian chính thức từ lúc bắt đầu chạy đến lúc chạm vạch đích (tính bằng giây).</p></li>
<li><p><code>net</code>: Thời gian ghi được (theo giây) từ lúc người chạy vượt qua vạch bắt đầu cho đến lúc chạm vạch đích. Giá trị này thường nhỏ hơn giá trị <code>time</code> do có một số lượng lớn người tham gia chạy, và không thể sắp xếp cho người tham gia đứng thẳng hàng để xuất phát cùng 1 lúc được (need citation here).</p></li>
<li><p><code>age</code>: Tuổi của người tham gia chạy tính bằng năm.</p></li>
<li><p><code>sex</code>: Giới tính người tham gia chạy, thuộc dạng <code>factor</code> với 2 giá trị <code>F</code> (female) vàdư <code>M</code> (male).</p></li>
</ul>
<p>Trước tiên, chúng ta cần phân biệt giữa 2 loại dữ liệu:</p>
<ol style="list-style-type: decimal">
<li><p>Discrete/Categorical (dữ liệu rời rạc): Là kiểu dữ liệu có giá trị nằm trong 1 tập hợp giới hạn có thể đếm được. Nếu dữ liệu là kiểu numeric, ta có thể gọi là Discrete, còn nếu là kiểu factor/string, ta gọi là Categorical. Ví dụ: Xếp hạng điểm của học sinh theo kiểu chữ cái (A/B/C/D/E/F) hoặc giới tính (Nam hoặc Nữ), hoặc số bữa ăn trong ngày (1 đến 3 bữa, thậm chí nhiều hơn, nhưng quan trọng là chúng ta có thể <em>đếm được</em>).</p></li>
<li><p>Continuous (dữ liệu liên tục): Là kiểu dữ liệu số có thể nhận một số giá trị vô hạn, không thể đếm được. Ví dụ: Chiều cao, cân nặng, thời gian/tuổi (ví dụ: Có thể nói là 10 tuổi, nhưng cũng có thể nói là 10 tuổi 5 tháng 20 ngày 7 phút 5 giây, vân vân).</p></li>
</ol>
<p>Tóm lại, khi làm việc với dữ liệu, chúng ta có thể tự đặt câu hỏi: “Liệu có thể chia các giá trị trong dataset này thành các phần nhỏ hơn hay không?”. Nếu có, dữ liệu sẽ thuộc kiểu liên tục.</p>
<div id="tóm-tắt-dữ-liệu-qua-đồ-thị" class="section level2">
<h2><span class="header-section-number">6.1</span> Tóm tắt dữ liệu qua đồ thị</h2>
<div id="một-biến-rời-rạc-univariate" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Một biến rời rạc (univariate)</h3>
<p>Chúng ta có thể dùng bar chart để mô tả phân phối của một biến rời rạc (đơn biến - univariate). Các cột (bar) được vẽ thể hiện một giá trị (level) của nhóm factor, và chiều cao của cột (nếu để biểu đồ dọc) thể hiện số quan sát (observation).</p>
<p>Ta cũng có thể dùng <code>group_by</code> và <code>summarise</code> để diễn giải bar chart như ở dưới:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1">TenMileRace <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb22-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb22-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">count =</span> <span class="kw">n</span>())</a></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   sex   count
##   &lt;fct&gt; &lt;int&gt;
## 1 F      4325
## 2 M      4311</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>sex)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Có thể thấy 2 cột có chiều cao tương đương nhau do số observation của mỗi giá trị factor gần bằng nhau (4325 vs. 4311). Như vậy, dữ liệu về người chạy đua trong data rất cân bằng về giới tính.</p>
</div>
<div id="một-biến-liên-tục-univariate" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Một biến liên tục (univariate)</h3>
<p>Đồ thị histogram nhìn khá giống với đồ thị bar chart, nhưng vì được sử dụng với biến liên tục nên các cột sẽ chạm vào nhau.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>net)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Chiều cao của mỗi cột trong đồ thị histogram thể hiện tần suất kết quả chạy theo các khoảng (interval), và trong R gọi là các bin (ngăn). Mặc định của hàm <code>geom_histogram</code> là <code>bins=30</code>, tức là mỗi khoảng cách nhau 30 đơn vị.</p>
<p>Ta có thể diễn giải lại biểu đồ trên dưới dạng bảng:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1">TenMileRace <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-2" title="2"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">bins=</span><span class="kw">cut</span>(net, <span class="dt">breaks=</span><span class="dv">30</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-3" title="3"><span class="st">    </span><span class="kw">group_by</span>(bins) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-4" title="4"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 29 x 2
##    bins                count
##    &lt;fct&gt;               &lt;int&gt;
##  1 (2.81e+03,3.07e+03]    18
##  2 (3.07e+03,3.33e+03]    22
##  3 (3.33e+03,3.59e+03]    65
##  4 (3.59e+03,3.84e+03]   131
##  5 (3.84e+03,4.1e+03]    197
##  6 (4.1e+03,4.36e+03]    339
##  7 (4.36e+03,4.62e+03]   495
##  8 (4.62e+03,4.87e+03]   685
##  9 (4.87e+03,5.13e+03]   735
## 10 (5.13e+03,5.39e+03]  1004
## # … with 19 more rows</code></pre>
<p>các interval trong bảng và đồ thị trên đều có mặc định là <span class="math inline">\((x, y]\)</span>, tức là <span class="math inline">\(x &lt; values &lt;= y\)</span> (right-closed, left-opened).</p>
<p>Chú ý: Đồ thị histogram dựa vào diện tích của các cột, không phải chiều cao, tức là bằng <span class="math inline">\(bin\;width\;*\;count\)</span>.</p>
</div>
<div id="một-biến-rời-rạc-và-một-biến-liên-tục-bivariate" class="section level3">
<h3><span class="header-section-number">6.1.3</span> Một biến rời rạc và một biến liên tục (bivariate)</h3>
<p>Chúng ta thường phải so sánh mức độ phản hồi (dữ liệu liên tục) của hai biến rời rạc hoặc nhiều hơn. Biểu đồ boxplot thường để sử dụng để làm việc này. Mỗi observation gắn với một giá trị liên tục và 1 giá trị rời rạc</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>sex, <span class="dt">y=</span>net)) <span class="op">+</span></a>
<a class="sourceLine" id="cb30-2" title="2"><span class="st">    </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Tron biểu đồ trên, phần rìa (hinge) của hộp được định nghĩa là các khoảng phần tư thứ nhất và thứ 3 (1st quartile, tương đương với 25% quantile, và 3rd quartile, đương tương với 75% quantile). Nói cách khác, 25% dữ liệu nằm dưới hộp, 50% nằm trong hộp, và phần 25% cuối cùng nằm phía trên hộp. Các điểm bên ngoài hộp là các outliers (điểm ngoại lai). Nếu định nghĩa Inter-Quartile Range (IQR) là chiều dài của hộp thì tất các quan sát lớn hơn 1.5*IQR tính từ hộp được coi như là 1 outlier.</p>
<p>Ngoài cách trên, chúng ta có thể dùng 2 đồ thị histogram đặt cạnh nhau để so sánh:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>net)) <span class="op">+</span></a>
<a class="sourceLine" id="cb31-2" title="2"><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb31-3" title="3"><span class="st">  </span><span class="kw">facet_grid</span>( . <span class="op">~</span><span class="st"> </span>sex )</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Trong trường hợp này, đồ thị đặt theo chiều dọc sẽ dễ so sánh hơn:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>net)) <span class="op">+</span></a>
<a class="sourceLine" id="cb32-2" title="2"><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb32-3" title="3"><span class="st">  </span><span class="kw">facet_grid</span>( sex <span class="op">~</span><span class="st"> </span>. ) <span class="co"># thay đổi chiều facet</span></a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="hai-biến-liên-tục-bivariate" class="section level3">
<h3><span class="header-section-number">6.1.4</span> Hai biến liên tục (bivariate)</h3>
<p>Để biểu diễn mối quan hệ của 2 biến liên tục, ta dùng biểu đô dạng điểm:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>age, <span class="dt">y=</span>net, <span class="dt">color=</span>sex)) <span class="op">+</span></a>
<a class="sourceLine" id="cb33-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
</div>
<div id="xu-hướng-trung-tâm" class="section level2">
<h2><span class="header-section-number">6.2</span> Xu hướng trung tâm</h2>
<p>Ngoài việc sử dụng các loại biểu đồ và đồ thị, chúng ta còn có thể dùng các 1 số chỉ số cơ bản để miêu tả dữ liệu. Mở đầu là các chỉ số về chiều hướng trung tâm (centrality).</p>
<div id="mean-trung-bình-cộng" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Mean (Trung bình cộng)</h3>
<p>Giá trị trung bình cộng (arithmetic mean, hay còn được gọi là average) là chỉ số cơ bản nhất, được tính theo công thức:</p>
<p><span class="math display">\[\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_{i}=\frac{1}{n}\left(x_{1}+x_{2}+\dots+x_{n}\right)\]</span></p>
<p>Trong R, ta tính mean bằng cách dùng hàm <code>mean()</code>:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="co"># Dùng base R</span></a>
<a class="sourceLine" id="cb34-2" title="2"><span class="kw">mean</span>(TenMileRace<span class="op">$</span>net)</a></code></pre></div>
<pre><code>## [1] 5599.065</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="co"># Dùng dplyr</span></a>
<a class="sourceLine" id="cb36-2" title="2"><span class="kw">summarise</span>(TenMileRace, <span class="kw">mean</span>(net))</a></code></pre></div>
<pre><code>##   mean(net)
## 1  5599.065</code></pre>
</div>
<div id="median-trung-vị" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Median (Trung vị)</h3>
<p>Median (trung vị) là giá trị ở giữa của 1 tập hợp dữ liệu đã sắp xếp theo thứ tự. Trong trường hợp số phần tự của tập hợp là số chẵn, ta lấy trung bình cộng của 2 giá trị ở giữa làm median, tức là lấy <span class="math inline">\((1/2)(y_{n/2}\;+\;y_{(n/2+1)})\)</span>.</p>
<p>Trong R, ta tính median bằng hàm <code>median()</code>:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">median</span>(TenMileRace<span class="op">$</span>net)</a></code></pre></div>
<pre><code>## [1] 5555</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="co"># Dùng dplyr</span></a>
<a class="sourceLine" id="cb40-2" title="2"><span class="kw">summarise</span>(TenMileRace, <span class="kw">median</span>(net))</a></code></pre></div>
<pre><code>##   median(net)
## 1        5555</code></pre>
</div>
<div id="trimmed-mean" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Trimmed mean</h3>
<p>Giá trị “trimmed mean” là giá trị trung bình sau khi “xén” bớt một số phần trăm nhất định ở 2 đầu phân phối; ví dụ đối với 5% trimmed mean, sau khi sắp xếp dữ liệu theo thứ tự, ta lấy bớt 5% các quan sát đầu tiên và cuối cùng, giữ lại 90% rồi lấy trung bình cộng.</p>
<p>Trong R, ta tính trimmed mean bằng hàm <code>mean()</code> kèm theo thông số <code>trim = n</code>:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">mean</span>(TenMileRace<span class="op">$</span>net, <span class="dt">trim=</span><span class="fl">0.5</span>)</a></code></pre></div>
<pre><code>## [1] 5555</code></pre>
<p>Có thể thấy, sau khi xén bớt 5% quan sát ở 2 đầu phân phối, mean và median của trường <code>net</code> trong dataset <code>TenMileRace</code> bằng nhau.</p>
</div>
<div id="ví-dụ" class="section level3">
<h3><span class="header-section-number">6.2.4</span> Ví dụ</h3>
<p>Một lớp học có 9 người, tuổi của cả lớp là tập hợp <span class="math inline">\(\{21, 22, 23, 25,26,22, 23,21, 26\}\)</span>. Mean của tập hợp là 23.222, median là 23; hai giá trị này hiện đang xấp xỉ nhau. Người thứ 10 nhập học có tuổi là 71, khiến mean của tập hợp trở thành 28.6, median vẫn giữ nguyên là 24. Giá trị mean mới lớn hơn so với median, do chúng ta thêm vào 1 outlier lớn hơn hẳn. Dữ liệu lúc này được gọi là lệch sang bên phải (skewed).</p>
<p>Đối với dữ liệu có độ lệch lớn, giá trị median sẽ thể hiện xu hướng trung tâm tốt hơn mean.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1">age &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">21</span>, <span class="dv">22</span>, <span class="dv">23</span>, <span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">22</span>, <span class="dv">23</span>,<span class="dv">21</span>, <span class="dv">26</span>)</a>
<a class="sourceLine" id="cb44-2" title="2"><span class="kw">mean</span>(age)</a></code></pre></div>
<pre><code>## [1] 23.22222</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">median</span>(age)</a></code></pre></div>
<pre><code>## [1] 23</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">age &lt;-<span class="st"> </span><span class="kw">append</span>(age, <span class="dv">71</span>) <span class="co"># thành viên mới của lớp học</span></a>
<a class="sourceLine" id="cb48-2" title="2"><span class="kw">mean</span>(age)</a></code></pre></div>
<pre><code>## [1] 28</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1"><span class="kw">median</span>(age)</a></code></pre></div>
<pre><code>## [1] 23</code></pre>
</div>
</div>
<div id="mức-độ-phân-tán-spreaddispersion" class="section level2">
<h2><span class="header-section-number">6.3</span> Mức độ phân tán (Spread/Dispersion)</h2>
<p>Câu hỏi thứ 2 khi làm việc với 1 dataset là “Mức độ phân tán của dataset này như thế nào?”. Ví dụ, ta có 2 tập dữ liệu có các tham số trung tâm tương đương nhau, nhưng không có nghĩa là 2 tập này giống nhau, mà dữ liệu có thể phân tán và biến thiên khác nhau. Có nhiều cách để trả lời câu hỏi này:</p>
<div id="range-khoảng-biến-thiên" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Range (Khoảng biến thiên)</h3>
<p><em>Range</em> (khoảng biến thiên) là khoảng cách giữa giá trị quan sát nhỏ nhất đến giá trị quan sát lớn nhất.</p>
<p><span class="math display">\[Range=Max-Min\]</span></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">TenMileRace <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb52-2" title="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">range =</span> <span class="kw">max</span>(net) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(net))</a></code></pre></div>
<pre><code>##   range
## 1  7722</code></pre>
</div>
<div id="inter-quartile-range" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Inter-Quartile Range</h3>
<p><em>Interquartile range</em> là khoảng cách giữa tứ phân vị thứ 3 (3rd quartile) và thứ phân vị thứ nhất (1st quartile):</p>
<p><span class="math display">\[IQR=Q3-Q1\]</span></p>
<p>Trước tiên, cần giải thích định nghĩa của các thuật ngữ <em>-tile</em>:</p>
<ul>
<li><p><strong>Percentile</strong>: Tiếng Việt nghĩa là “bách phân vị”; sau khi xếp dữ liệu theo thứ tự, giá trị phần trăm thứ <span class="math inline">\(p\)</span> (<span class="math inline">\(p_{th}\)</span> percentile) là giá trị quan sát có <span class="math inline">\(p\)</span> phần trăm số quan sát bên dưới và <span class="math inline">\((1-p)\)</span> bên trên, trong đó <span class="math inline">\(p\)</span> nằm giữa 0 và 100. Percentile thứ 0 và 100 là chính là giá trị nhỏ nhất và lớn nhất của tập dữ liệu. Giá trị <em>median</em> là giá trị phần trăm thứ 50 (50th percentile). Percentile là một <em>mốc</em>, không phải 1 <em>khoảng</em> dữ liệu.</p></li>
<li><p><strong>Quartile</strong>: Thông thường, chúng ta sẽ chia dữ liệu ra làm 4 phần với 3 mốc 25th percentile, 50th percentile và 75th percentile, tức là chia dữ liệu ra làm 4 phần. Ba mốc này cũng được gọi là 1st, 2nd và 3rd quartiles (khoảng phần tư thứ nhất, thứ 2 và thứ 3).</p></li>
<li><p><strong>Quantile</strong>: Là các điểm cắt/điểm mốc chia một khoảng phân phối xác suất ra thành các khoảng với xác suất giống nhau. Như vậy, <strong>quartile</strong> và <strong>percentile</strong> là các trường hợp đặc biệt của quantile.</p></li>
</ul>
<p>Dùng hàm <code>quantile()</code>:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">quantile</span>(TenMileRace<span class="op">$</span>net)</a></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
##  2814  4950  5555  6169 10536</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="co"># so sánh giá trị 0%, 50% và 100%</span></a>
<a class="sourceLine" id="cb56-2" title="2"><span class="co"># với các hàm min, max và median</span></a>
<a class="sourceLine" id="cb56-3" title="3"><span class="kw">c</span>(<span class="kw">min</span>(TenMileRace<span class="op">$</span>net),</a>
<a class="sourceLine" id="cb56-4" title="4">  <span class="kw">median</span>(TenMileRace<span class="op">$</span>net),</a>
<a class="sourceLine" id="cb56-5" title="5">  <span class="kw">max</span>(TenMileRace<span class="op">$</span>net))</a></code></pre></div>
<pre><code>## [1]  2814  5555 10536</code></pre>
<p>Chúng ta có thể dùng argument <code>probs</code> trong hàm <code>quantile()</code> để tìm ra các percentile khác:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">quantile</span>(TenMileRace<span class="op">$</span>net, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.05</span>, <span class="fl">0.95</span>))</a></code></pre></div>
<pre><code>##      5%     95% 
## 4098.75 7260.50</code></pre>
<p>Giá trị mặc định của argument <code>probs</code> là 0 (min), 0.25 (1st quartile), 0.5 (2nd quartile/median), 0.75 (third quartile) và 1 (max).</p>
<p>Để tính IQR, chúng ta hàm <code>IQR</code> (nhớ viết hoa):</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="kw">IQR</span>(TenMileRace<span class="op">$</span>net)</a></code></pre></div>
<pre><code>## [1] 1219</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="co"># hoặc kết hợp với dplyr</span></a>
<a class="sourceLine" id="cb62-2" title="2">TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="kw">IQR</span>(net))</a></code></pre></div>
<pre><code>##   IQR(net)
## 1     1219</code></pre>
<p>Lưu ý: hàm <code>quantile</code> mặc định trả về 5 giá trị, vì vậy sẽ không kết hợp được với <code>dplyr::summarise</code> do hàm <code>summarise</code> chỉ trả về 1 kết quả. Nếu thay đổi argument <code>probs</code> thì có thể kết hợp được.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1">TenMileRace <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">quantile</span>(net, <span class="dt">probs =</span> <span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>##   quantile(net, probs = 0.5)
## 1                       5555</code></pre>
</div>
<div id="variance-phương-sai" class="section level3">
<h3><span class="header-section-number">6.3.3</span> Variance (Phương sai)</h3>
<p>Trước tiên, ta xem xét khoảng cách từ một quan sát bất kì đến mean (<em>deviation</em>). Ta định nghĩa deviation thứ <span class="math inline">\(i_{th}\)</span> là:</p>
<p><span class="math display">\[e_{i}=x_{i}-\bar{x}\]</span></p>
<p>Vậy khoảng cách trung bình đến mean là bao nhiêu? Nếu khảo sát mức độ phân tán bằng cách này, ta gặp phải 2 vấn đề:</p>
<ol style="list-style-type: decimal">
<li>Tổng của tất cả các khoảng cách từ các quan sát đến mean bằng 0:</li>
</ol>
<p><span class="math display">\[\sum_{i=1}^{n}(x_{i}-\bar{x}) =   \sum_{i=1}^{n}x_{i}-\sum_{i=1}^{n}\bar{x}
    =   n\frac{1}{n}\sum_{i=1}^{n}x_{i}-n\bar{x}
    =   n\bar{x}-n\bar{x}
    =   0\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Vấn đề lớn hơn: Các giá trị khoảng cách đến mean có cả giá trị âm và dương, và khi khảo sát mức độ phân tán, kết quả âm hay dương là vô nghĩa. Để giải quyết vấn đề này, chúng ta có thể lấy giá trị tuyệt đối hoặc bình phương kết quả.</li>
</ol>
<p>Nếu đi theo hướng lấy giá trị tuyệt đối, ta dùng chỉ số MAD (<em>Mean Absolute Deviation</em>), được tính là trung bình của tổng giá trị tuyệt đối của khoảng cách từ các observation đến mean: <span class="math inline">\((1/n)\sum_{i=1}^{n}|x_{i}-\bar{x}|\)</span>.</p>
<p>Nếu đi theo hướng bình phương kết quả, ta dùng phương sai (<em>variance</em>). Trong thực tế, dữ liệu thường ở dạng một phân phối chuẩn (normal distribution - sẽ nhắc đến ở phần 2), như chiều cao con người, huyết áp, điểm thi, giá cổ phiếu, v.v. Phân phối chuẩn được định nghĩa bởi 2 thông số là mean và variance, và vì mức độ quan trọng của phân phối chuẩn, nên variance được sử dụng nhiều hơn khi tính toán mức độ phân tán.</p>
<ol style="list-style-type: decimal">
<li><p><em>Sample variance</em> (Phương sai mẫu), với <span class="math inline">\(\bar{x}\)</span> là giá trị trung bình cộng của mẫu, <span class="math inline">\(n\)</span> là số observation:
<span class="math display">\[s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_{i}-\bar{x})^2\]</span></p></li>
<li><p><em>Population variance</em> (Phương sai quần thể), với <span class="math inline">\(\mu\)</span> là giá trị trung bình cộng của quần thể, <span class="math inline">\(n\)</span> là số observation:
<span class="math display">\[\sigma^{2}=\frac{1}{n}\sum_{i=1}^{n}(x_{i}-\mu)^2\]</span></p></li>
</ol>
<p>Dữ liệu thu thập được thường ở dạng một mẫu của cả quần thể. Nếu trong trường hợp có dữ liệu của cả population, ta sẽ dùng công thức 2. Ở cả 2 công thức, ta lấy tổng bình phương của khoảng cách tới mean, sau đó lấy trung bình, tuy nhiên ta chia cho <span class="math inline">\((n-1)\)</span> để tính <em>sample variance</em> (phương sai mẫu) thay vì chia cho <span class="math inline">\(n\)</span> để tính <em>population variance</em> (phương sai quần thể). Ta làm điều này để tránh việc (<span class="math inline">\(\sigma^{2}\)</span>) bị “biased” - có nghĩa là nếu dùng công thức tính population variance cho một sample, kết quả tính ra thường <em>nhỏ</em> hơn bình thường (do ta đang tính <span class="math inline">\(s^2\)</span>, vốn là 1 chỉ số ước lượng (estimator), dựa trên 1 chỉ số ước lượng khác là <span class="math inline">\(\bar{x}\)</span>).</p>
<p>Để tính sample variance trong R, chúng ta sử dụng hàm <code>var()</code>:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="kw">var</span>(TenMileRace<span class="op">$</span>net)</a></code></pre></div>
<pre><code>## [1] 940233.5</code></pre>
</div>
<div id="standard-variation-độ-lệch-chuẩn" class="section level3">
<h3><span class="header-section-number">6.3.4</span> Standard variation (độ lệch chuẩn)</h3>
<p>Vấn đề lớn nhất của sample variance là đơn vị ở dạng bình phương, dẫn đến việc gây khó hiểu, khó để dẫn đến kết luận/phân tích. Để giải quyết, ta lấy giá trị căn bậc 2 để có được độ lệch chuẩn mẫu (sample standard deviation).</p>
<p><span class="math display">\[s=\sqrt{s^2}\]</span></p>
<p>Để tính độ lệch chuẩn mẫu trong R, ta dùng hàm <code>sd()</code>:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">sd</span>(TenMileRace<span class="op">$</span>net)</a></code></pre></div>
<pre><code>## [1] 969.6564</code></pre>
<p>Về mặt toán học, phương sai quan trọng hơn vì nó được sử dụng làm định nghĩa cho các phân phối xác suất, nhưng độ lệch chuẩn dễ hiểu hơn và vì thế có ích trong thực tế hơn.</p>
</div>
<div id="hệ-số-biến-thiên-coefficient-of-variation" class="section level3">
<h3><span class="header-section-number">6.3.5</span> Hệ số biến thiên (Coefficient of variation)</h3>
<p>Chúng ta xem xét ví dụ sau: Có 1 nhóm động vật có độ lệch chuẩn mẫu của chiều dài con vật là 15cm. Chỉ với thông tin này, ta gần như không thể đưa ra kết luận gì có ích. Giả sử có thêm thông tin về loài động vật:</p>
<ul>
<li><p>Nếu là voi: ta có thể kết luận nhóm các con voi này có chiều dài rất đồng đều, do chiều dài trung bình của cả loài voi nói chung sẽ lớn hơn 15cm rất nhiều, và ta có thể dựa vào common sense để nhận định rằng chiều dài giữa các con voi trong nhóm lệch nhau rất nhỏ.</p></li>
<li><p>Nếu là côn trùng: ta có thể kết luận nhóm côn trùng này có chiều dài rất đa dạng, thậm chí là có nhiều loài côn trùng khác nhau. Trong thực tế, loài côn trùng dài nhất cũng có chỉ độ dài khoảng 60cm.</p></li>
</ul>
<p>Như vậy, nếu có thêm thông tin về loài động vật, hay nói cách khác là thông tin giúp ta ước lượng được <strong>chiều dài trung bình</strong> của nhóm động vật trên, ta sẽ đưa ra được nhiều kết luận có ích.</p>
<p>Để giải quyết vấn đề này, ta có thể dùng hệ số biến thiên:</p>
<p><span class="math display">\[CV = \frac{s}{|\bar{x}|}\]</span></p>
</div>
<div id="quy-tắc-thực-nghiệm" class="section level3">
<h3><span class="header-section-number">6.3.6</span> Quy tắc thực nghiệm</h3>
<p>Ta có thể sử dụng quy tắc thực nghiệm như sau để áp dụng cho các mẫu dữ liệu tương đối lớn và đối xứng:</p>
<table>
<thead>
<tr class="header">
<th align="center">Khoảng</th>
<th align="center">Số lượng phần trăm quan sát (tương đối)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(\bar{x}\pm s\)</span></td>
<td align="center">68.3%</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\bar{x}\pm 2s\)</span></td>
<td align="center">95.5%</td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(\bar{x}\pm 3s\)</span></td>
<td align="center">99.7%</td>
</tr>
</tbody>
</table>
<p><img src="_main_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
</div>
</div>
<div id="tiếp-tục-với-biểu-đồ" class="section level2">
<h2><span class="header-section-number">6.4</span> Tiếp tục với biểu đồ</h2>
<div id="box-plot" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Box plot</h3>
</div>
<div id="scatter-plot" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Scatter plot</h3>
</div>
<div id="skewness-kurtosis" class="section level3">
<h3><span class="header-section-number">6.4.3</span> Skewness &amp; Kurtosis</h3>
</div>
</div>
<div id="tổng-hợp-thuật-ngữ" class="section level2">
<h2><span class="header-section-number">6.5</span> Tổng hợp thuật ngữ</h2>
</div>
<div id="một-số-bài-tập" class="section level2">
<h2><span class="header-section-number">6.6</span> Một số bài tập</h2>
</div>
<div id="tham-khảo" class="section level2">
<h2><span class="header-section-number">6.7</span> Tham khảo</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="xác-su-t-c-b-n.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
